
INSERT INTO permissions VALUES (1, 'STARTER_PAGE');
INSERT INTO permissions VALUES (2, 'ADD_WEIGHT_PAGE');
INSERT INTO permissions VALUES (3, 'WEIGHT_HISTORY_PAGE');
INSERT INTO permissions VALUES (4, 'CHART_PAGE');
INSERT INTO permissions VALUES (5, 'PERSONAL_DATA_PAGE');
